name = "12th MEU Assets"
prefix = "12thMEU"
author = "Sammy"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
    "logo.paa",
    "README.md",
    "LICENSE",
    "*.pbo"
]

[version]
major = 7
minor = 0
patch = 6
build = 1
git_hash = 4